[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "0659e4abb7f1a8dc4bf791620757b4ebdcf9d778"
libgfortran_version = "5.0.0"
os = "macos"

    [[FMM3D.download]]
    sha256 = "43c985f4495d2854d7e28e8a474edb95ea6a76bd321c43a3788267555480f68e"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "242848a2c86e013658272cd45c322afd4c1297e5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "791d1aad87b100b16ec7ece53950b39c324f15e0112081c82a2b5276ade0a03f"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "b719a3308e66408d917f480ef93481c5112303ff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "ea07c1700971f00010a1ac53391825d12db2f87b7dc9d2f4df98be2892447e00"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "bb9fee33c4f987e4c681e7b44bc3d85d6b805ec0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FMM3D.download]]
    sha256 = "14bec2eaab72a3d39c9dae7441e7e38afde5d481eb5de5807a38f4522ef0d042"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "49d71ebf31d155648872c9a34d115eead4242aea"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "639f92be7ad6ebba01e96e2b047e1b208672b334d52fe0fe6d15164a42057407"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e4ef6ac96f618ddbd45eb76cf4a82bf2e0c9942d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "6ee4b9920bf208f332c8c9648dc3e91f535f27b19b47b3e02b1f315aa21362f9"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b9e6f6859c8cd9d091ac76172d8a02827648fdb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "e46064cbc5a27e806bfec50cc7624732cfc83ae324589155d62fde28b10c2ca4"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "305e34612c3077d56149dfa94bf6194ddd76af09"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "e8ce83bf7e1eec833169dcd9b9ae4b5cf1bd4f7466f00ca86f76bafc395859e3"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "d2bd3980ca47b4f0f48abc331f3a6798932e996c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "1bd24c56c85791be1423e86c7a547e54816422d2b303ab36cd5de5ce6222100e"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "8295cb98e39a3b8d5e6336875afe0483dce86b24"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "050eaedf42347a56a5f9681196c3e175ee4646816c5a12aff1cc371b22033d9b"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "c3bcb7b5133cdba810659573c6a631ac34d6721b"
libgfortran_version = "5.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "ae221da1304d49dc3803912a6cbc61d4d50986b395a1184965518f55a4cff36b"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[FMM3D]]
arch = "powerpc64le"
git-tree-sha1 = "af7c2cd4adcc493684603ccdd65f5e34193ff65e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "524f652c1ce71ebea8b00eeb6a37abffbd35efe1bc36332bca971aa07df7478b"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "riscv64"
git-tree-sha1 = "92b11e3d1f0f37d99236821448a83819381a2f51"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "1c5882f08d77e453e06fbe4c77db8da7ff015d416238baeae142e8cce0b15bcc"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "d529c32b3b1f56e77d86a102b3aa272a48136c06"
libgfortran_version = "5.0.0"
os = "macos"

    [[FMM3D.download]]
    sha256 = "c6c14fbcb864606b124f572d102eb8dc41d17b89ac5de44830978664a9e59786"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "93e48feb269440a05dd7cedd32d102f2e0f927b5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "ee0789b09b92ceda1dcf362f7a556e1dbb6a51efed112b62a78b0eb03debf723"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "c2a61009330a9b3cf4063aaf85692a1810fdea62"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "017b666190a8135ba8d1c6a1dd1635067c6e108f834cddb4119f4332a94751f8"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "3e83408c5db30cdb45a4bbee39805fdb66e8ecc0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FMM3D.download]]
    sha256 = "20e395b581bf2edde1eb1af3a34d1dcdf199324ed883808d1397a28b6d856fd5"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "c2492b740f54baaaf255887857febc8cc8ec243a"
libgfortran_version = "5.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "470b6388fb41269ba37f50da6aaa797dfd646aba80fc4ca1996f8c78e673962f"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v2.1.0+0/FMM3D.v2.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
