[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "79a0803a167e3ac24e11b4ed9d81145a92fd1a19"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "7dcbe159a1b872a02514a31f07dabaae4186393138cc817eb6c7f5be0517f8e0"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "cbc7e0c0914dbf21652054ad81e6b308ad2623f5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "2958f540286f84ac915b7cef54184f1d83b600676a2de1d0eabcc4a033408930"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "2f034cfb943d4330850c9579a9737bd6f84b0e6e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "5d6665e467fa606cc9f6f98f08cbec382c588f5c8744971d188c4d95698c3c60"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "dfe9cf54b957539e5e0783d5b77b1a0ec8f99ff6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "d2ed36ffa64edce37e2b99d8203de45ee4f3ed2b812de1cef625013176f77615"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "a45286bafdaf1b62921c13b433e224102df05b64"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "b05f9c6a2035c9ff7f1255f96050c1759c9c1bec469f561f7a06d528f610fe53"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[FMM3D]]
arch = "aarch64"
git-tree-sha1 = "c4e03e3f41d7de047746b178a7fd48c2ea9873d4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "b8446d1a49895fdcb2a18ccd4b16c9b4d61ac2e1bfe53c74413884cf1674bd54"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85eee79940742de540e143806d3bccbd45335aee"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "4c5ac4da53e497d3f831a45cb788444513cf694539a326a77f319a79aae8092b"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39fc864822fbf05217d03f5f2772ea4866e32117"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "3dde70a608c42ebe9725d803e4885b5099649a7935268c98ccb4b1013fe7af47"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d10f4eba9a4cca758f60cec5b1955c654bc6801"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "47be6bdfa7ff23c308292adfb0e30bf5cb2d93754bcae8a391b9d8ca9e7e1705"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b44e43b2b22b1d5b7b9eea1859e3d598822c6d8c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "8f35870fb01f1be727b6111c7175d4ead1ac10567ae4818f0b1138e8f9a51de8"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "305fa4a6c50b0222fcb38d91d1aa46e084ee0a6d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "410cd57e7e6696eac5967a2d72cb2427ea65248eabf4262f3c9d26f6ea61982c"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[FMM3D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a73c739f9514bf511097564a7e256202f561cd55"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "b01106da531a08de19c54f177345e48b5852f470aa68e4acd1dce66c28a52379"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "afbc26bc1d017ca73a64d36994f0d2cefa8bc396"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "5e7fed103bc0f29da93ae6ed60fb95ebec584298f3cc7347b13059815b0dca33"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0925b4c2fea51867a40deb259c15e90298c72e1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "9ba34e42aba83ac61a4be20f68880b652ba220218ae782dd7b9aee80ed7b41c7"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "862b268909987f3bd9d78f6c6b69e18dbc12c96c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "d77ac67daa959fb0c76cbc2aa3628a36d98164f6aa6558226e8449d5264c03ae"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13154eeace381a64bf4ba42d29ec0a3102120d67"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "b7be637de807574f6919b608771d8b3e68472240136ecbc757851360fd9473d6"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b1bb63fe52deb6f4ea01110c693f68081ed55433"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "f3ec00a56acc7014a77ed2650262f8f97fbe7e554b403a8bfa8fb86dc526f3b3"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FMM3D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0e67dd10d9eab15d0bd400d6d45f6d05098b47b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "d193f797bc73fb8de4c159ea475505ad1c133a0745348955d776fcf138b2808e"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "d653422a63bba0d4063a0cb4d5b521480d85bb3c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "bc5a79c66ecb2edb90914752755d7882f6104192560c2d54ccb58f6200113e7e"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "2e95fb022b474c41b176658744f115afa19ac77a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "5490b4048558b5ede6d0da11511dadcebc20bf6e1485c73e5b72ca9f5ec22b9c"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "49dbd16b089939f0452325e55e587fc2718174c5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "dd3730c4da18bb98497ae3f90db10a58321bff6d9ae373caf3bcbbba618420f3"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "0fa5d01a1a4f1d365fba86dd708d755bc762b557"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "7060fc98ae4a9916e987b224346801d50b31ce5988a59740fa638870a83736a5"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "e9263e90270b2fe8693c87aa00ba19329a8643ce"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "5fc6c6e10f9e35638501ee4fe273939c966939ff99a81af9112099f75e5ad514"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "df13aabf5844e603443302dcd7005ece310b1cbd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "eb4be1e13250ad9c0c360a1ea1866cbcccc946bcb04b44f470407398ca191eb0"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "3dbaf4a5dcefc13cef32868c25562b616adac7c5"
libgfortran_version = "3.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "931326da7308d0539fc4e8c2dc06366c0d227250d54379b9e7e10841636bc97e"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "f80b0cc6715e56243ad736c0866363d783402329"
libgfortran_version = "4.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "54de4b065af09d085789111e1714ee6669d133263190fd63b3c31004dcbfbe8d"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[FMM3D]]
arch = "i686"
git-tree-sha1 = "8d1cd29971da7caf57b726bf094f0d50a22f6563"
libgfortran_version = "5.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "51a33cfe45b04863ba5bb1e632af0a6ea3df7aab3913e3e6ab0642b0bf707191"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[FMM3D]]
arch = "powerpc64le"
git-tree-sha1 = "de00b8add0af2c9a076adb555ee3b4259b9c869e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "f7964937e51f13171cb128657130bfebc6e632ee7f844833879f0ca1fe99f879"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[FMM3D]]
arch = "powerpc64le"
git-tree-sha1 = "dcd5f9d9a06ef23824dcdb2f8e4b3016a4c9d07f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "479ab01104b6d3956ee2ad848c94a27d42ed0785adb9201c373c4c386e617aaa"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[FMM3D]]
arch = "powerpc64le"
git-tree-sha1 = "c2893923a0885131d919fd6ecbc86cc363cfd953"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "9957c98d707670fbfdb1f63eedd3df8a175052ee5fbecaac6c0008fc06ac27fb"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "9c387d45a65deba3b06b4f42477f43c3292cb80e"
libgfortran_version = "3.0.0"
os = "macos"

    [[FMM3D.download]]
    sha256 = "35cd8170a19b37b37d1f48657f6dfc07ee1591dea1ee3eeec368fd090a46d785"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "cb76b90ffe3fcfab22352f7de295090c7d74b831"
libgfortran_version = "4.0.0"
os = "macos"

    [[FMM3D.download]]
    sha256 = "9f7526169a25ed08a41794e7cab0ddee3915090dff403906b35411b3c4da5181"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "ed33e90b9b293a26b8fb0489a93e9cef7bce22d7"
libgfortran_version = "5.0.0"
os = "macos"

    [[FMM3D.download]]
    sha256 = "2a1a5d1ad6ea6d0be53c0c64f64de1feecaac2b7197e7846094d1461c77537f6"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "bc4e69d3a23a098ce3c707b778cbce6fd51686a2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "395676f42a0ac73c497308e3d0ce03bb2e642b1f3cd21c26d4708f6d6d181a0d"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "ebafd8960681c7c40767b45acf55add68446470d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "7277ee07750c6880805e7778dd6cb7c22574eb7f2b1e44e7f073621382026605"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "f3c802ee0d13688a0dad24f10fce0476d33b4b7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "4935e34d1a697d21e20d9ddad8739d27e0c3880071e7bd3d23f8f355d274894f"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "db8898a8f19e5a199de3e3924b7302792c7bbd60"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "5b6786d1b43483adc9408de280c8769c586a706df22535336f130fa8a5da6a64"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "1a803febc9f547d2229c1d851914ff3de179cdf2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "d5ebd70fddd89d57108e35f7836b5e9528e8740db8cfe0cdcdbb6a14529a044f"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "4ce9f362c345964d368e513eb6b955ef3ced1a87"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM3D.download]]
    sha256 = "7168d58c5416899f4fb4c6287dc44efe16499f0f45e89dcf47bd46058f24819e"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "2fbe328cf4bd8df74522f8fe6a586d6311226833"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FMM3D.download]]
    sha256 = "213cedb9b33e2294d60f9a4d9794b8bb0a5cbb9dff844dc0d5d484b9a1a9f4f7"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "0815be5126495e340c8fb7bd6085958baebe9bec"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FMM3D.download]]
    sha256 = "bef3dd953ed6f91b23b9ffac2239e17a935773226ba33197ce3a91abf9a09ba8"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "b080d9715ea706871d8a8351e7909e8a306f52d3"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FMM3D.download]]
    sha256 = "73843151a3e6903e95e1790e387ed5d07f47d6e9a2b1be911ee6bb12dd38ff04"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "bf8aeb9742f64d34a65959566a22790e8860df28"
libgfortran_version = "3.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "5ac496bbd2ce480469780cfb9d6365e74ed0f6e24850c3d74b668589a67bcc6d"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "2f351a902489a2c97045d8350c3c177b3bc4aef3"
libgfortran_version = "4.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "e19cf9dcb2993301d31067f42ba80dc8e370c2c950da8a14140a18280617b15b"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FMM3D]]
arch = "x86_64"
git-tree-sha1 = "bdeac7a8cdbf76412ca63ab096e3a8c9dad0d9f8"
libgfortran_version = "5.0.0"
os = "windows"

    [[FMM3D.download]]
    sha256 = "82468d544883e7a0bf5cd72295443086581ba6078ee53572102d3205a17468e7"
    url = "https://github.com/JuliaBinaryWrappers/FMM3D_jll.jl/releases/download/FMM3D-v0.1.0+0/FMM3D.v0.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
