# Autogenerated wrapper script for FMM3D_jll for aarch64-apple-darwin-libgfortran5
export libfmm3d

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("FMM3D")
JLLWrappers.@declare_library_product(libfmm3d, "@rpath/libfmm3d.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libfmm3d,
        "lib/libfmm3d.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
